#!/usr/bin/env bash
#---------------------------
# script    : config-tela
# Descrição : configura brilho tela
# Versão    : 0.1
# Autor     : Marciano
# Data      : 25/12/2022
# Licença   : GNU/GPL v3.0
# --------------------------
# Uso       : config-tela, digitar o valor
# --------------------------

read -p "Digite o brilho de 1 a 9: " brilho

[[ ! $brilho =~ ^[1-9]$ ]] && echo "Apenas número de 1 a 9" && exit 1

xrandr --output VGA-1 --brightness 0.$brilho

exit 0
