#!/usr/bin/env bash
#---------------------------
# script    : config-tela
# Descrição : configura brilho tela
# Versão    : 0.1
# Autor     : Marciano
# Data      : 25/12/2022
# Licença   : GNU/GPL v3.0
# --------------------------
# Uso       : config-tela, digitar o valor
# --------------------------

brilho=$(zenity --text="Digite de 1 a 9" --entry)

[[ ! $brilho =~ ^[0-9]+$ ]] && zenity --info --text="Apenas números." && exit 1

[[ $brilho -gt 9 || $brilho -le 1 ]] && zenity --info --text="Seu numero deve ser entre 1 e 9 " && exit 1

xrandr --output HDMI-1 --brightness 0.$brilho
