#!/usr/bin/env bash

#---------------------------
# script    : run-emulator
# Descrição : iniciar emulador
# Versão    : 0.1
# Autor     : Marciano
# Data      : 22/12/2022
# Licença   : GNU/GPL v3.0
# --------------------------
# Uso       : programação flutter
# --------------------------


device=$(/path/android/emulator/emulator -list-avds)

declare -a devices=()

for i in $device
do
    devices+=($i)
done

emulador=$(
zenity --list \
 	 --title="Emuladores" \
 	--column="Emulador" \
	"${devices[@]}" \
)

[[ $emulador == "" ]] && exit 0

/path/flutter/bin/flutter emulators --launch $emulador && exit 1

echo 0

